### ISSUE TITLE
pip install android-resource-remover, fail

### ISSUE THREAD

**Issue by rambowding** [KeepSafe/android-resource-remover#19]
RambowdeMacBook-Pro:~ rambow$ pip install android-resource-remover
Collecting android-resource-remover
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached android-resource-remover-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/df/b8ktrgmx1hz761_0wy30v_zw0000gn/T/pip-build-GyYpfS/android-resource-remover/setup.py", line 14, in <module>
        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),
      File "/private/var/folders/df/b8ktrgmx1hz761_0wy30v_zw0000gn/T/pip-build-GyYpfS/android-resource-remover/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/df/b8ktrgmx1hz761_0wy30v_zw0000gn/T/pip-build-GyYpfS/android-resource-remover/README.md'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/df/b8ktrgmx1hz761_0wy30v_zw0000gn/T/pip-build-GyYpfS/android-resource-remover

**Comment by rambowding** [comment]
RambowdeMacBook-Pro:~ rambow$ pip --version
pip 6.1.1 from /Library/Python/2.7/site-packages (python 2.7)
RambowdeMacBook-Pro:~ rambow$ python --version
Python 2.7.6

**Comment by rambowding** [comment]
on windows, has the same error
C:\Windows\System32>pip install android-resource-remover
Collecting android-resource-remover
D:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:79: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading android-resource-remover-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\dingxi~1\appdata\local\temp\pip-build-v8b4oc\android-resour
ce-remover\setup.py", line 14, in <module>
        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),
      File "c:\users\dingxi~1\appdata\local\temp\pip-build-v8b4oc\android-resour
ce-remover\setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    IOError: [Errno 2] No such file or directory: 'c:\\users\\dingxi~1\\appdata\
\local\\temp\\pip-build-v8b4oc\\android-resource-remover\\README.md'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\ding
xi~1\appdata\local\temp\pip-build-v8b4oc\android-resource-remover

C:\Windows\System32>

**Comment by ca77y** [comment]
fixed in `0.1.4`
