### ISSUE TITLE
Why i got an error when running android-resource-remover

### ISSUE THREAD

**Issue by CharonChui** [KeepSafe/android-resource-remover#20]
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python\Scripts\android-resource-remover.exe\__main__.py", line 9, in
<module>
  File "D:\Python\lib\site-packages\android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "D:\Python\lib\site-packages\android_clean_app.py", line 78, in run_lint_
command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "D:\Python\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "D:\Python\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by ca77y** [comment]
please check if `lint` command is in you PATH

**Comment by philippb** [comment]
@CharonChui can you please check fi the `lint` command is in your path. otherwise we close this issue. Thanks

**Comment by adamkis** [comment]
I get the same error, and I have lint in my path

pip install android-resource-remover
Downloading/unpacking android-resource-remover
  Downloading android-resource-remover-0.1.4.tar.gz
  Running setup.py (path:/tmp/pip_build_akis/android-resource-remover/setup.py) egg_info for package android-resource-remover
    
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.3 in /usr/lib/python2.7/dist-packages (from android-resource-remover)
Installing collected packages: android-resource-remover
  Running setup.py install for android-resource-remover
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/android_clean_app.py'
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_akis/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DmuZMG-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying android_clean_app.py -> build/lib.linux-x86_64-2.7

running install_lib

copying build/lib.linux-x86_64-2.7/android_clean_app.py -> /usr/local/lib/python2.7/dist-packages

error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/android_clean_app.py'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_akis/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DmuZMG-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_akis/android-resource-remover
Storing debug log for failure in /home_local/akis/.pip/pip.log

**Comment by ca77y** [comment]
this is not the same error. this is a permissions problem when installing android-resource-remover
