### ISSUE TITLE
Does not keep newline at end of file and xml header

### ISSUE THREAD

**Issue by ypresto** [KeepSafe/android-resource-remover#26]
Unnecessary change is applied when remover modifies content of xml files.

```diff
-<?xml version="1.0" encoding="utf-8"?>
+<?xml version='1.0' encoding='UTF-8'?>
```

```diff
-</resources>
+</resources>
\ No newline at end of file
```

**Comment by ca77y** [comment]
we use lxml for parsing and it will unfortunately strip whitespace characters after and before root element. https://bugs.launchpad.net/lxml/+bug/526799
