### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by PsHype** [KeepSafe/android-resource-remover#28]
In file included from src/lxml/lxml.etree.c:239:
    /private/var/folders/_p/xb0p4rxn50z_nzvv_1vj9mkw0000gq/T/pip-build-3XWO9K/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
    Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/var/folders/_p/xb0p4rxn50z_nzvv_1vj9mkw0000gq/T/pip-build-3XWO9K/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_p/xb0p4rxn50z_nzvv_1vj9mkw0000gq/T/pip-XQZTXI-record/install-record.txt --single-version-externall

**Comment by PsHype** [comment]
sudo C_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2/libxml:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include

The Solution above

**Comment by ca77y** [comment]
readme updated, thx
