### ISSUE TITLE
It does not work with Android Studio Lint Result

### ISSUE THREAD

**Issue by Gankerzzl** [KeepSafe/android-resource-remover#34]
I used Android Studio->Analyze->Inspect Code to get a lint result and export to xml named AndroidLintUnusedResources.xml. Then I used command 'python android-resource-remover --xml AndroidLintUnusedResources.xml' , but it does not work. Anything I did wrong?
[AndroidLintUnusedResources.txt](https://github.com/KeepSafe/android-resource-remover/files/37836/AndroidLintUnusedResources.txt)

**Comment by ca77y** [comment]
thanks for reporting, i'll look into it

**Comment by ca77y** [comment]
those are not lint results generated by the lint included in Android SDK, the structure is completely different. you can check the example https://github.com/KeepSafe/android-resource-remover/blob/master/test/android_app/lint-result.xml
