### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by binglingziyu** [KeepSafe/android-resource-remover#37]
bogon:~ hubin$ pip install android-resource-remover
Collecting android-resource-remover
  Using cached android-resource-remover-0.1.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.3 in /Library/Python/2.7/site-packages (from android-resource-remover)
Installing collected packages: android-resource-remover
  Running setup.py install for android-resource-remover
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/t0/sl2174ps6dq7__dr4cbvrm7h0000gn/T/pip-build-IAYg_g/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/t0/sl2174ps6dq7__dr4cbvrm7h0000gn/T/pip-9aRlIK-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying android_clean_app.py -> build/lib
    running install_lib
    copying build/lib/android_clean_app.py -> /Library/Python/2.7/site-packages
    error: could not delete '/Library/Python/2.7/site-packages/android_clean_app.py': Permission denied

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/t0/sl2174ps6dq7__dr4cbvrm7h0000gn/T/pip-build-IAYg_g/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/t0/sl2174ps6dq7__dr4cbvrm7h0000gn/T/pip-9aRlIK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/t0/sl2174ps6dq7__dr4cbvrm7h0000gn/T/pip-build-IAYg_g/android-resource-remover

**Comment by binglingziyu** [comment]
bogon:~ hubin$ sudo pip install android-resource-remover
Password:
The directory '/Users/hubin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hubin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting android-resource-remover
  Downloading android-resource-remover-0.1.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.3 in /Library/Python/2.7/site-packages (from android-resource-remover)
Installing collected packages: android-resource-remover
  Running setup.py install for android-resource-remover
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Tegqhi/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bC4yPh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying android_clean_app.py -> build/lib
    running install_lib
    copying build/lib/android_clean_app.py -> /Library/Python/2.7/site-packages
    byte-compiling /Library/Python/2.7/site-packages/android_clean_app.py to android_clean_app.pyc
    running install_data
    copying AUTHORS -> /System/Library/Frameworks/Python.framework/Versions/2.7/.
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/./AUTHORS'

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Tegqhi/android-resource-remover/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bC4yPh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Tegqhi/android-resource-remover

**Comment by ca77y** [comment]
seems a problem with your permissions. try installing it in virtual env
