### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by manyata** [KeepSafe/android-resource-remover#44]
@ca77y So i ran your tool with lint results xml file and it gave me a bunch of output mentioning removing strings ... 
all the output was mentioning removal of strings from libraries that are used inside the project, none of the actual unused resources from strings.xml and drawable folders were removed. I ran lint again in android studio and all the unused icons were still there

**Comment by tobiasandersson** [comment]
I have a similar issue. Unused resources are only removed from the build/intermediates/ folder, not from source folders.

**Comment by manyata** [comment]
@ca77y any idea?

**Comment by ca77y** [comment]
hi guys. sorry to hear that. i'll look into it over the weekend. con you provide me with any details, something specific with your project. there is a sample app in the test folder, maybe you can reproduce the problem with it?

**Comment by manyata** [comment]
cannot repro with the test module. it works perfectly there. but still not working with my app :(
