### ISSUE TITLE
pin install error

### ISSUE THREAD

**Issue by ernestp** [KeepSafe/android-resource-remover#46]
Python 2.7.10
pip 7.1.1 from /Library/Python/2.7/site-packages (python 2.7)
Mac OS X 10.11.4
Xcode 7.3

Same error with easy_install

    Building lxml version 3.6.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.11-intel-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/usr/include/libxml2 -Isrc/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.11-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    In file included from src/lxml/lxml.etree.c:320:
    src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    Compile failed: command 'cc' failed with exit status 1
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/g7/_2r9d3rx1w5d_jl0kf2h5w7r0000gp/T/xmlXPathInitLGKTsq.c -o var/folders/g7/_2r9d3rx1w5d_jl0kf2h5w7r0000gp/T/xmlXPathInitLGKTsq.o
    /var/folders/g7/_2r9d3rx1w5d_jl0kf2h5w7r0000gp/T/xmlXPathInitLGKTsq.c:1:10: fatal error: 'libxml/xpath.h' file not found
    #include "libxml/xpath.h"
             ^
    1 error generated.

**Comment by snejku** [comment]
@ernestp 
Please check this:

> Q: installing dependency lxml failed with fatal error: 'libxml/xmlversion.h' file not found
> A: There are several ways to fix this listed on stackoverflow http://stackoverflow.com/questions/19548011/cannot-install-lxml-on-mac-os-x-10-9
