### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by shingohu** [KeepSafe/android-resource-remover#50]
sudo -H pip install android-resource-remover
Requirement already satisfied (use --upgrade to upgrade): android-resource-remover in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.3 in /Library/Python/2.7/site-packages (from android-resource-remover)

I have no idea ,could you help me?

**Comment by ca77y** [comment]
please check the readme
