### ISSUE TITLE
Does this tool support latest gradle android project structure?

### ISSUE THREAD

**Issue by amatkivskiy** [KeepSafe/android-resource-remover#53]
Hi guys, thanks for such cool tool.
When I try to run it with lint XML file it fails. It says that manifest file can't be found.

`IOError: [Errno 2] No such file or directory: '/Projects/Project/app/AndroidManifest.xml'`

**Comment by ypresto** [comment]
Use below snippet to workaround until this is fixed:

```
android-resource-remover --app app/src/main --xml `pwd`/app/build/reports/lint-results-yourBuildVariant.xml
```

**Comment by msj2** [comment]
- I am on Android Studio 3.2.1
- lint is in SDK Folder
- I ran Lint & exported the XML to home directory.
-  I had lots of XML files (like AndroidLint*.xml, Unnecessary*.xml......)
- I only have the Debug APK ...
- I tried running android-resource-remover as below

>  android-resource-remover --lint ~/Android/Sdk/tools/lib/lint-26.0.0-dev.jar

`Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 11, in <module>
    load_entry_point('android-resource-remover==0.1.7', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 196, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 96, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
`

with or without sudo, I get the same error

Can I get help..
