### ISSUE TITLE
Add a feature that remove all unused classes,methods from Android Studio project

### ISSUE THREAD

**Issue by aheadlcx** [KeepSafe/android-resource-remover#58]
hi,guy:
Could you add a feature that remove all unused classes,methods from Android Studio project.
It maybe is what many people expect .
such as  [link](http://stackoverflow.com/questions/37066506/remove-all-unused-classes-methods-from-android-studio-project)

**Comment by ca77y** [comment]
this tool does not analyze/edit the source code and there are no plans for this functionality right now
