### ISSUE TITLE
unicodeDecodeerror

### ISSUE THREAD

**Issue by t12x3456** [KeepSafe/android-resource-remover#6]
I run the command "pip instatll android-resource-remover", then received an error like that:
unicodeDecodeerror gbk codec can't decode byte 0x80

**Comment by ca77y** [comment]
can you paste the whole output

**Comment by t12x3456** [comment]
This is my error screenshot:
![2](https://cloud.githubusercontent.com/assets/5113264/5751857/37e03c1a-9ca5-11e4-928c-413709c42c0e.jpg)

**Comment by t12x3456** [comment]
I modified the encoding of python file like that: "# encoding=utf8  import sys    reload(sys)  sys.setdefaultencoding('utf8')", but it did't work.

**Comment by ca77y** [comment]
screenshot is not what i had in mind :)

you should have pip log somewhere like C:\Users\username\pip\pip.log

please remove it, run pip and paste the content here

**Comment by YangShaoXiong** [comment]
I also encountered a similar error, as follows:

C:\Users\Administrator>pip install android-resource-remover
Collecting android-resource-remover
  Using cached android-resource-remover-0.1.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-31t6tc25\android-reso
urce-remover\setup.py", line 14, in <module>
        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-31t6tc25\android-reso
urce-remover\setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 916: ille
gal multibyte sequence
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-31t6tc25\android-reso
urce-remover\setup.py", line 14, in <module>

        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),

      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-31t6tc25\android-reso
urce-remover\setup.py", line 8, in read

        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()

    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 916: ille
gal multibyte sequence

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMI
NI~1\AppData\Local\Temp\pip-build-31t6tc25\android-resource-remover

**Comment by ca77y** [comment]
i can't reproduce this issue. if this is something you still have a problem with please provide:

1. your system setup (os, python version, pip version, anything specific you think is relevant)
2. attach pip error log file

you can also tell me when you'll be available and catch me on gitter [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/KeepSafe/android-resource-remover?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
