### ISSUE TITLE
The lint parser add an extra '`' in the resource name which don't remove the res value

### ISSUE THREAD

**Issue by eboudrant** [KeepSafe/android-resource-remover#9]
The lint parser add an extra '`' in the resource name which don't remove the res value
```
removing ('string', 'loading_more`') from resource res/values/strings.xml
```
Used OSX Maverick with an output of Gradle Lint :

```
<?xml version="1.0" encoding="UTF-8"?>
<issues format="4" by="lint 24.0.1">
...
```

**Comment by philippb** [comment]
Can you please specify the bug more.
What build tool version are you using, gradle version.

Also if you're not using the latest build tool/platform tool version, can you please verify if that is still a problem on the latest versions.
Thank you

**Comment by eboudrant** [comment]
I am using lint 24.0.1, it is probably not the latest but still a recent version.

The problem is in the xml, the message format has changed, some quote were added :
```
message="The resource `R.string.loading_more` appears to be unused"
```

Looks like the python script accept only without quotes : 
```
message="The resource R.string.loading_more appears to be unused"
```

This fixed my problem : 
```
-    L25 : pattern = re.compile('The resource (.+) appears to be unused')
+    L25 : pattern = re.compile('The resource `(.+)` appears to be unused')
```

But I am not sure since when the format has changed.

Thanks

**Comment by ca77y** [comment]
We should probably support both. I have a look into it

**Comment by ca77y** [comment]
fixed
